spring.application.name=SportRadar
spring.config.import=optional:file:.env.properties

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sportradar_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true